# Generated by Django 5.1.4 on 2025-10-28 19:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cedula', models.CharField(db_index=True, help_text='Número de documento de identidad', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números', regex='^\\d+$')])),
                ('nombres_completos', models.CharField(help_text='Nombres completos del usuario', max_length=200)),
                ('fecha_expedicion', models.DateField(help_text='Fecha de expedición del documento')),
                ('idcaso_biometria', models.CharField(blank=True, db_index=True, help_text='ID del caso en el sistema del proveedor', max_length=50, null=True)),
                ('estado_biometria', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', help_text='Estado actual de la validación biométrica', max_length=20)),
                ('justificacion_biometria', models.TextField(blank=True, help_text="Mensaje del proveedor (ej: 'E01. Cedula OK, confronta facial OK')", null=True)),
                ('fecha_validacion_biometria', models.DateTimeField(blank=True, help_text='Cuándo se completó la validación biométrica', null=True)),
                ('fecha_inicio_linix', models.DateTimeField(blank=True, help_text='Cuándo el usuario fue redirigido a LINIX', null=True)),
                ('id_tercero_linix', models.CharField(blank=True, db_index=True, help_text='ID del tercero generado en LINIX (tabla gr_tercero)', max_length=50, null=True)),
                ('flujo_linix_creado', models.BooleanField(default=False, help_text='True cuando Oracle confirma que el flujo se creó correctamente')),
                ('datos_oracle', models.JSONField(blank=True, help_text='Datos completos retornados por el procedimiento Oracle', null=True)),
                ('estado_vinculacion', models.CharField(choices=[('INICIADO', 'Iniciado'), ('BIOMETRIA_OK', 'Biometría Aprobada'), ('EN_LINIX', 'Completando en LINIX'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], db_index=True, default='INICIADO', help_text='Estado general del proceso', max_length=30)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Cuándo se completó todo el proceso exitosamente', null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si algo falló en el proceso', null=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, help_text='IP desde donde se inició el proceso', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador del usuario', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
            ],
            options={
                'verbose_name': 'Pre-Registro',
                'verbose_name_plural': 'Pre-Registros',
                'db_table': 'vinculacion_preregistro',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_cedula'], name='vinculacion_numero__ccc67f_idx'), models.Index(fields=['estado_vinculacion'], name='vinculacion_estado__ed8eab_idx'), models.Index(fields=['estado_biometria'], name='vinculacion_estado__13d1d6_idx'), models.Index(fields=['created_at'], name='vinculacion_created_ab3f2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CONSULTA_BIOMETRIA', 'Consulta Estado Biometría'), ('VERIFICACION_ORACLE', 'Verificación en Oracle'), ('WEBHOOK_N8N', 'Webhook a n8n')], help_text='Tipo de operación', max_length=50)),
                ('exitoso', models.BooleanField(help_text='True si fue exitoso, False si hubo error')),
                ('request_data', models.JSONField(blank=True, help_text='Datos enviados en la petición', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Datos recibidos en la respuesta', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo ocurrió')),
                ('preregistro', models.ForeignKey(help_text='Pre-registro asociado', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vinculacion.preregistro')),
            ],
            options={
                'verbose_name': 'Log de Integración',
                'verbose_name_plural': 'Logs de Integración',
                'db_table': 'vinculacion_log_integracion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['preregistro', 'created_at'], name='vinculacion_preregi_101fa9_idx'), models.Index(fields=['accion'], name='vinculacion_accion_f50b06_idx')],
            },
        ),
    ]
