# Generated by Django 5.1.4 on 2025-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='agencia',
            field=models.CharField(blank=True, help_text='Agencia seleccionada por el usuario para la vinculación', max_length=100, null=True),
        ),
    ]
