# Generated by Codex on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0002_preregistro_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='tipo_documento',
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[
                    (1, 'Cédula de ciudadanía'),
                    (2, 'Tarjeta de identidad'),
                    (3, 'Registro civil'),
                    (4, 'Cédula de extranjería'),
                    (5, 'Documento definido por la DIAN'),
                    (6, 'NIT'),
                    (7, 'P.E.P.'),
                    (8, 'Pasaporte'),
                    (9, 'Visa'),
                ],
                help_text='Tipo de documento según catálogo DECRIM'
            ),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='url_biometria',
            field=models.URLField(
                blank=True,
                null=True,
                max_length=500,
                help_text='URL generada por DECRIM para continuar el proceso'
            ),
        ),
    ]
