# Generated by Django 5.1.4 on 2026-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0003_preregistro_tipo_documento_url_biometria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintegracion',
            name='accion',
            field=models.CharField(choices=[('CONSULTA_BIOMETRIA', 'Consulta Estado Biometría'), ('REGISTRO_DECRIM', 'Registro en DECRIM'), ('VERIFICACION_ORACLE', 'Verificación en Oracle'), ('WEBHOOK_N8N', 'Webhook a n8n')], help_text='Tipo de operación', max_length=50),
        ),
    ]
