"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located in backend/
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

if not SECRET_KEY:
    if DEBUG:
        # Fallback only for local development if .env is missing
        SECRET_KEY = "dev-secret-key-change-me"
    else:
        raise RuntimeError("SECRET_KEY is not set; please define it in .env or environment.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost,192.168.15.215,consulta.congente.coop'
    ).split(',')
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', '')
DECRIM_API_URL = os.environ.get(
    'DECRIM_API_URL',
    'https://consultorid.com/api/digital/crear/registro.php'
)
DECRIM_USERNAME = os.environ.get(
    'DECRIM_USERNAME',
    os.environ.get('USER_DECRIM', os.environ.get('NAME_DECRIM', ''))
)
DECRIM_PASSWORD = os.environ.get(
    'DECRIM_PASSWORD',
    os.environ.get('PASSWORD_DECRIM', '')
)

ORACLE_USER = os.environ.get('ORACLE_USER', os.environ.get('ORACLE_DB_USER', ''))
ORACLE_PASSWORD = os.environ.get('ORACLE_PASSWORD', os.environ.get('ORACLE_DB_PASSWORD', ''))
ORACLE_DSN = os.environ.get('ORACLE_DSN')
if not ORACLE_DSN:
    oracle_host = os.environ.get('ORACLE_DB_HOST', '')
    oracle_port = os.environ.get('ORACLE_DB_PORT', '')
    oracle_name = os.environ.get('ORACLE_DB_NAME', '')
    if oracle_host and oracle_port and oracle_name:
        ORACLE_DSN = f"{oracle_host}:{oracle_port}/{oracle_name}"
    else:
        ORACLE_DSN = ''

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'rest_framework',
    'corsheaders',

    # Local Apps
    'vinculacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS Middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Settings (configurable via env)
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'False').lower() == 'true'
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": os.environ.get("DB_PORT", ""),
    },
    'oracle': {
        'ENGINE': os.environ.get('ORACLE_DB_ENGINE'),
        'NAME': os.environ.get('ORACLE_DB_NAME'),
        'USER': os.environ.get('ORACLE_DB_USER'),
        'PASSWORD': os.environ.get('ORACLE_DB_PASSWORD'),
        'HOST': os.environ.get('ORACLE_DB_HOST'),
        'PORT': os.environ.get('ORACLE_DB_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
