"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located in backend/
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

if not SECRET_KEY:
    if DEBUG:
        # Fallback only for local development if .env is missing
        SECRET_KEY = "dev-secret-key-change-me"
    else:
        raise RuntimeError("SECRET_KEY is not set; please define it in .env or environment.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost,192.168.15.215,consulta.congente.coop'
    ).split(',')
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', '')
DECRIM_ENV = os.environ.get('DECRIM_ENV', 'qa').lower()
DECRIM_API_URL = os.environ.get(
    'DECRIM_API_URL',
    'https://consultorid.com/api/digital/crear/registro.php'
)
_decrim_consulta_default_url = (
    'https://dev.consultorid.com/api/validacion/consultar/caso.php'
    if DECRIM_ENV == 'qa'
    else 'https://consultorid.com/api/validacion/consultar/caso.php'
)
DECRIM_CONSULTA_URL = os.environ.get(
    'DECRIM_CONSULTA_URL',
    _decrim_consulta_default_url
)
DECRIM_CONSULTA_CANAL = os.environ.get('DECRIM_CONSULTA_CANAL', '0')
DECRIM_CONSULTA_CERTIFICADO = os.environ.get('DECRIM_CONSULTA_CERTIFICADO', '0')
DECRIM_WEBHOOK_USER = os.environ.get('DECRIM_WEBHOOK_USER', '')
DECRIM_WEBHOOK_PASSWORD = os.environ.get('DECRIM_WEBHOOK_PASSWORD', '')
DECRIM_WEBHOOK_JWT_SECRET = os.environ.get('DECRIM_WEBHOOK_JWT_SECRET', '')
DECRIM_WEBHOOK_TOKEN_TTL = int(os.environ.get('DECRIM_WEBHOOK_TOKEN_TTL', '300'))
DECRIM_WEBHOOK_IP_WHITELIST = [
    ip.strip()
    for ip in os.environ.get('DECRIM_WEBHOOK_IP_WHITELIST', '').split(',')
    if ip.strip()
]
DECRIM_USERNAME = os.environ.get(
    'DECRIM_USERNAME',
    os.environ.get('USER_DECRIM', os.environ.get('NAME_DECRIM', ''))
)
DECRIM_PASSWORD = os.environ.get(
    'DECRIM_PASSWORD',
    os.environ.get('PASSWORD_DECRIM', '')
)
MAX_INTENTOS_BIOMETRIA = int(os.environ.get('MAX_INTENTOS_BIOMETRIA', '2'))
DEV_SKIP_DECRIM = os.environ.get('DEV_SKIP_DECRIM', 'False').lower() == 'true'
DEV_BIOMETRIA_AUTO_APPROVE = os.environ.get('DEV_BIOMETRIA_AUTO_APPROVE', 'False').lower() == 'true'

# LINIX API (Vinculacion agil - Paso 3)
LINIX_API_BASE_URL = os.environ.get('LINIX_API_BASE_URL', 'http://consulta.congente.coop:8041')
LINIX_TOKEN_URL = os.environ.get('LINIX_TOKEN_URL', '')
LINIX_VINCULACION_URL = os.environ.get('LINIX_VINCULACION_URL', '')
LINIX_TOKEN_PATH = os.environ.get('LINIX_TOKEN_PATH', '/api/v1/incluirtec/token/')
LINIX_VINCULACION_PATH = os.environ.get('LINIX_VINCULACION_PATH', '/api/v1/incluirtec/radicarAfiliacion/')
LINIX_CLIENT_ID = os.environ.get('LINIX_CLIENT_ID', '')
LINIX_CLIENT_SECRET = os.environ.get('LINIX_CLIENT_SECRET', '')
LINIX_TIMEOUT = int(os.environ.get('LINIX_TIMEOUT', '30'))
LINIX_TOKEN_CACHE_KEY = os.environ.get('LINIX_TOKEN_CACHE_KEY', 'linix_access_token')
LINIX_TOKEN_CACHE_SAFETY_SECONDS = int(os.environ.get('LINIX_TOKEN_CACHE_SAFETY_SECONDS', '60'))
LINIX_DEFAULT_COUNTRY_CODE = os.environ.get('LINIX_DEFAULT_COUNTRY_CODE', '169')
LINIX_DEFAULT_AUTORETENEDOR = os.environ.get('LINIX_DEFAULT_AUTORETENEDOR', 'N')
LINIX_DEFAULT_TIPO_CON = os.environ.get('LINIX_DEFAULT_TIPO_CON', 'D')
LINIX_DEFAULT_TIPO_CUENTA = os.environ.get('LINIX_DEFAULT_TIPO_CUENTA', 'A')
LINIX_DEFAULT_VALOR_FACTOR = os.environ.get('LINIX_DEFAULT_VALOR_FACTOR', '1')
LINIX_DRY_RUN = os.environ.get('LINIX_DRY_RUN', 'False').lower() == 'true'
LINIX_VERIFICACION_DRY_RUN = os.environ.get('LINIX_VERIFICACION_DRY_RUN', 'False').lower() == 'true'
LINIX_CATALOG_DEFAULTS = {
    'A_UBICACION_UNO': os.environ.get('LINIX_A_UBICACION_UNO', '1'),
    'A_UBICACION_DOS': os.environ.get('LINIX_A_UBICACION_DOS', '1'),
    'A_SECCION': os.environ.get('LINIX_A_SECCION', '1'),
    'A_CENCOS': os.environ.get('LINIX_A_CENCOS', '1'),
    'A_CARGO': os.environ.get('LINIX_A_CARGO', '1'),
    'A_DEPENDENCIA': os.environ.get('LINIX_A_DEPENDENCIA', '1'),
    'A_ESTADO_LABORAL': os.environ.get('LINIX_A_ESTADO_LABORAL', 'A'),
    'A_TIPO_CONTRATO': os.environ.get('LINIX_A_TIPO_CONTRATO', '01'),
}

ORACLE_USER = os.environ.get('ORACLE_USER', os.environ.get('ORACLE_DB_USER', ''))
ORACLE_PASSWORD = os.environ.get('ORACLE_PASSWORD', os.environ.get('ORACLE_DB_PASSWORD', ''))
ORACLE_DSN = os.environ.get('ORACLE_DSN')
if not ORACLE_DSN:
    oracle_host = os.environ.get('ORACLE_DB_HOST', '')
    oracle_port = os.environ.get('ORACLE_DB_PORT', '')
    oracle_name = os.environ.get('ORACLE_DB_NAME', '')
    if oracle_host and oracle_port and oracle_name:
        ORACLE_DSN = f"{oracle_host}:{oracle_port}/{oracle_name}"
    else:
        ORACLE_DSN = ''

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'rest_framework',
    'corsheaders',

    # Local Apps
    'vinculacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS Middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Settings (configurable via env)
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'False').lower() == 'true'
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": os.environ.get("DB_PORT", ""),
    },
    'oracle': {
        'ENGINE': os.environ.get('ORACLE_DB_ENGINE'),
        'NAME': os.environ.get('ORACLE_DB_NAME'),
        'USER': os.environ.get('ORACLE_DB_USER'),
        'PASSWORD': os.environ.get('ORACLE_DB_PASSWORD'),
        'HOST': os.environ.get('ORACLE_DB_HOST'),
        'PORT': os.environ.get('ORACLE_DB_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
